# Generated by Django 2.2.8 on 2021-06-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'depart__title': '教育部'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='crm.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tech_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'depart__title__in': ['Linux教学部', 'Python教学部']}, related_name='teach_classes', to='crm.UserInfo', verbose_name='任课老师'),
        ),
    ]
