# Generated by Django 2.2.8 on 2021-06-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210601_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlist',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='classlist',
            name='tech_teachers',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
